// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace donk.Models;

public partial class LoginSession
{
    public int Id { get; set; }

    public Guid SessionId { get; set; }

    public int UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public DateTime ExpireAt { get; set; }

    public virtual Users User { get; set; }
}