// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace donk.Models;

public partial class WishlistItems
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public string UserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Products Product { get; set; }
}